### PR TITLE
update personal adaptation

### PR DESCRIPTION
**Pull request by BorisKingma**
as agreed with Lars on the definition of personal adaptation follows 

was: wbgt+cav / (RAL)
is : wbgt+cav / (RAL - PAV)

PAV = personal adjustment value

UI
- personal adjustment of recommended alert limit directly with buttons.

-- for this version I removed functionality (temporarily):
 - store history of adjustments (DIFF is always a 1 element array)

--
moved legacy 'feedback' to personalisation (advanced personalisation).

### CODE REVIEW

**Comment by frksteenhoff** [comment]
Hi Boris, 
Is it crucial that I review this right away? I would love to steer clear of coding until I hand in my thesis Wednesday next week.

**Comment by Chuansi-LU** [comment]
PAV = personal adjustment value looks good, make a try. 
we need to make it clear that on the Dashboard or under More Info, "Your personal indication is baesd on your personal adjustment". Clearly distinguish between personal WBGT_pav and WBGT_iso_cav, i.e. what the user has adjusted and what ISO recommends (making personal responsibility clear). Add one more parameter, WBGT_pav, under More Info?

BTW, I am announcing ClimApp in some social media, and have noticed there are different versiosn (Android: 1.0.0, iOS 1.3, knowledge base 2.033). Are these latest versions? is it necessary to update/sync these versions as the same verison?

Feedbakc from a user in Beijing today: 39 C, mean radian temperature reached 95.5 C ?

**Comment by Chuansi-LU** [comment]
A picture from the fantastic ICEE in Amsterdam.
BTW, Did you notice and visit this poster where you are a co-author? If you missed, try to involve more users, test Climapp and give suggestions.

Best
Chuansi

Från: Boris <notifications@github.com>
Skickat: den 25 juli 2019 01:26
Till: frksteenhoff/ClimApp <ClimApp@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: [frksteenhoff/ClimApp] update personal adaptation (#126)


as agreed with Lars on the definition of personal adaptation follows

was: wbgt+cav / (RAL)
is : wbgt+cav / (RAL - PAV)

PAV = personal adjustment value

UI

  *   personal adjustment of recommended alert limit directly with buttons.

-- for this version I removed functionality (temporarily):

  *   store history of adjustments (DIFF is always a 1 element array)

--
moved legacy 'feedback' to personalisation (advanced personalisation).

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/frksteenhoff/ClimApp/pull/126

Commit Summary

  *   update personal adaptation

File Changes

  *   M cordova/climapp/www/css/index.css<https://github.com/frksteenhoff/ClimApp/pull/126/files#diff-0> (3)
  *   M cordova/climapp/www/js/index.js<https://github.com/frksteenhoff/ClimApp/pull/126/files#diff-1> (97)
  *   M cordova/climapp/www/pages/feedback.html<https://github.com/frksteenhoff/ClimApp/pull/126/files#diff-2> (11)
  *   M cordova/climapp/www/pages/settings.html<https://github.com/frksteenhoff/ClimApp/pull/126/files#diff-3> (9)

Patch Links:

  *   https://github.com/frksteenhoff/ClimApp/pull/126.patch
  *   https://github.com/frksteenhoff/ClimApp/pull/126.diff

**Comment by frksteenhoff** [comment]
Hi Chuansi, 

As Boris previously wrote, he is on holiday and I am finalizing my thesis (as I also wrote earlier in this thread), which limits the amount of work that we will be able to do.

It is nice that you want to share information about ClimApp, but if you want us to act upon something it would be nice if you would give us more time than what is the case here -- informing us on the day you are doing something. For me, this is very frustrating as this makes the process (at least for me) more stressful that I think is necessary and it is harder to find the time to get the work done.. Please consider that changing something also takes time and we are not available for development purposes every moment of the day. Furthermore, as Boris already mentioned, the iOS process for publishing takes longer time.

Different versions do not mean that they are not working separately.

Again, I want to stress that I will not be working on any code until I am back in September after my defense and holiday.

Enjoy your summer :-)

**Comment by BorisKingma** [comment]
No need. Was trying to follow protocol

Op do 25 jul. 2019 10:12 schreef Henriette Steenhoff <
notifications@github.com>:

**Comment by frksteenhoff** [comment]
Great 👍 I'll get to it as soon as I have the time!

**Comment by Chuansi-LU** [comment]
Hi Henriette,
Sorry, if my emails make you stressful. I try to do more tests and involve more users during summer as it is the high reason because when the weather is moderate, not many users are interested in using it. Once I come accross some issues, I send comments/feedback, but this does not mean you need to fix the issues at once, no deadline is given, just let the feedback be listed here or stored in the email, you can respond when you have time. I have told Boris in one of my emails.
Best
Chuansi

**Pull request merged**
