### PR TITLE
Partial merge of changes into master

### PR DESCRIPTION
**Pull request by frksteenhoff**
### Complications
This pull request contains the same content as #133 - adding a merge step is the only difference. 

I have checked that the content overall is rendered correctly and that the app overall is well-functioning, however there still are some problems that I am not able to resolve by myself.

* The indoor module only allow the user to set `temperature` and `open windows`
  * Currently, the function [`getIndoorPrediction`](https://github.com/frksteenhoff/ClimApp/blob/master/cordova/climapp/www/js/helper_functions/dtu_database.js#L137) takes 8 parameters, 5 input by the user, 3 with default values. If these values are not provided, the response from the server will only be a default value which is undesirable.
  *  The module also need to allow for configuration of `thermostat`, `humidity` and `wind speed` as a minimum (all of these are working as part of my changes in #133) Some code has been commented out in [indoor.html](https://github.com/frksteenhoff/ClimApp/blob/master/cordova/climapp/www/pages/indoor.html) -- because of the PMV implementation? As I am not familiar with the inner workings of the PMV related implementation and how my changes might affect them, I cannot make the right changes.
  * `Indoor temperature` should not be an option within the module (that is what we are measuring) _but it is included to make the PMV implementation work, or?_
* Because of changes to how the `translations.json` file is fetched and updated, I cannot verify that the changes I made in the app are correct after merging.
  * I have added a new `translations.json` file with the updated information
  * There are no Swedish translations of the `feedback` pane, Swedish translations are left out due to this.

### CODE REVIEW

**Comment by BorisKingma** [comment]
Hi Henriette, nice to hear from you.

with respect to this point: "The module also need to allow for configuration of thermostat, humidity and wind speed as a minimum (all of these are working as part of my changes in #133) Some code has been commented out in indoor.html -- because of the PMV implementation? As I am not familiar with the inner workings of the PMV related implementation and how my changes might affect them, I cannot make the right changes." 

As previously discussed, we cannot assume the user knows humidity. we decided to use outdoor humidity and air temperature to calculate outdoor vapour pressure. We assume vapour pressure is equal inside and outside of the building. Then we calculate the indoor humidity with the estimated indoor temperature.

for this flow to work:
1. I can send outdoor relative humidity and outdoor temperature, is that consistent with what the indoor module expects?
- i will discuss with Jorn today as well.

**Comment by frksteenhoff** [comment]
Hi Boris 😄 

That makes total sense, and yes it is hard for the user to know/measure the relative humidty -- this was what I agreed upon with Jørn, so I thought everyone agreed on this.

Outdoor relative humidity and temperature will be fine -- in #133 the temperature is already passed to the API, so doing the same for relative humidity should be an easy fix.

**Comment by frksteenhoff** [comment]
I also saw in `indoor.html` that some of the text is hard coded, this should probably be changed to work with the translation module? 

https://github.com/frksteenhoff/ClimApp/blob/master/cordova/climapp/www/pages/indoor.html#L30

**Comment by BorisKingma** [comment]
#133 is merged with master- solved conflicts

**Pull request closed without merging**
